# Generated by Django 5.1.5 on 2025-01-21 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('is_toprank', models.BooleanField(default=False)),
                ('chicken_entries', models.JSONField(default=list)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='ToprankEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('is_toprank', models.BooleanField(default=True)),
                ('chicken_entries', models.JSONField(default=list)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
    ]
