# Generated by Django 5.1.5 on 2025-01-21 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entries_toprankentries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded', models.JSONField(default=list)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
    ]
