# Generated by Django 5.1.5 on 2025-02-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_excludedentries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_number', models.IntegerField()),
                ('entry_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('chicken_name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('matched_entry_name', models.CharField(max_length=100)),
                ('matched_owner_name', models.CharField(max_length=100)),
                ('matched_chicken_name', models.CharField(max_length=100)),
                ('matched_weight', models.FloatField()),
            ],
        ),
    ]
