# Generated by Django 5.1.5 on 2025-02-04 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
